#!/usr/bin/expect

set FILE [lindex $argv 0]
set PW [lindex $argv 1]

set timeout 5

log_user 0
spawn ssh-keygen -t rsa
expect {
    "id_rsa):" {
        send -- "${FILE}\n"
        exp_continue
    }
    "passphrase):" {
        send -- "${PW}\n"
        exp_continue
    }
    "again:" {
        send -- "${PW}\n"
    }
}

expect {
    -regexp "\n.*\r" {
        log_user 1
        send "exit\n"
        exit 0
    }
}
