#!/usr/bin/expect

set FILE [lindex $argv 0]
set PW [lindex $argv 1]
set OPTIONS [lindex $argv 2]

set timeout 5
set Prompt "\[#$%>\]"

log_user 0
spawn ssh-add $OPTIONS $FILE
expect {
    ":" {
        send -- "${PW}\n"
    }
}

expect {
    -glob "${Prompt}" {
        exit 0
    }
}
